### ISSUE TITLE
[BUG] TypeError: MyFAISS.similarity_search_with_score_by_vector() got an unexpected keyword argument 'filter'

### ISSUE THREAD

**Issue by lucasjinreal** [imClumsyPanda/langchain-ChatGLM#739]
TypeError: MyFAISS.similarity_search_with_score_by_vector() got an unexpected keyword argument 'filter'

**Comment by LMC117** [comment]
Hi,

I encountered the same problem and found that it was caused by the langchain version. The newer versions of langchain have altered the parameters of similarity_search_with_score() in faiss.py. 

To resolve this, you could try **downgrading your langchain version to 0.0.174** and see if it resolves the problem (this works for me).

**Comment by bk007lz** [comment]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/109656343/d43a13d2-1222-4143-9a01-92a3f3120ea6)
已经升级掉0.0.174 仍然存在该问题
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/109656343/77b69ead-9b86-42db-892c-2f2a4846c944)
